version: '3.9'

services:
  db:
    image: 
    restart: always
    environment:
     POSTGRES_DB: himnn
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: 1234
    ports:
      - '127.0.0.1:5432:5432'

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '127.0.0.1:1337:1337'
    depends_on:
      - db

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - server
